# Generated by Django 4.1.7 on 2023-03-27 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='related_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
