# Generated by Django 4.1.7 on 2023-03-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='private_account',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
