# Generated by Django 4.1.7 on 2023-03-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_friendrequest_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_posts',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
