# Generated by Django 4.1.7 on 2023-03-31 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_customuser_hello'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hello',
        ),
    ]
