# Generated by Django 4.1.7 on 2023-03-31 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_customuser_hello'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='friends',
        ),
    ]
