# Generated by Django 4.1.7 on 2023-03-31 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recomendation', '0002_alter_recommendation_options_and_more'),
        ('account', '0017_customuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='recommendations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='recomendation.recommendation'),
        ),
    ]
