# Generated by Django 4.1.7 on 2023-03-31 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_customuser_recommendations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('from_user', 'to_user')},
        ),
    ]
