# Generated by Django 4.1.8 on 2023-04-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_customuser_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='discord_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
