# Generated by Django 4.1.8 on 2023-04-24 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='post_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
