# Generated by Django 4.1.7 on 2023-03-31 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('D', 'Dialog'), ('C', 'Chat')], default='D', max_length=1, verbose_name='Type')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Member')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is read')),
                ('author', models.ForeignKey(on_delete=models.SET('deleted'), to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat', verbose_name='Chat')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
    ]
