# Generated by Django 4.1.7 on 2023-03-31 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recomendation', '0003_alter_recommendation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommend', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
