# Generated by Django 4.1.7 on 2023-03-31 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_post_favorite'),
        ('recomendation', '0004_alter_recommendation_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='members',
            field=models.ManyToManyField(related_name='recommend_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='posts',
            field=models.ManyToManyField(related_name='recommend_posts', to='post.post'),
        ),
    ]
